name: digital_lcd_number
description: An automatic sizer digital single-digit number with LCD style widget.
version: 0.1.2
# homepage:
repository: https://github.com/immadisairaj/digital_lcd_number

screenshots:
  - description: 'All Digits in LCD style red color.'
    path: example/screenshots/all_digits.png

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
